### ISSUE TITLE
Usb printers power off and avahi-deamon

### ISSUE THREAD

**Issue by xavier7179** [DrPsychick/docker-cups-airprint#35]
I'm using the docker with happiness until I turn off the USB printer (a Canon MP240 if useful) but not the server. Then I still spend hours trying to make it work (putting the printer properly on the network again).

I noticed that in logs if I restart the server, I find the following error:

```
Unable to communicate with avahi-daemon: Access denied
```

Am I doing something wrong? Should it be fine to power off the printer while the server is still running?

**Comment by xavier7179** [comment]
I did some extra work and investigation. Actually, if I only restart the container, it's not enough. I need to remove the printer on the docker-compose service environment variables, the start it again and add the printer again. This makes the printer available everywhere

**Comment by DrPsychick** [comment]
That seems strange. If you've configured the printer through environment variables it should be added/setup with every start of the container.

Can you maybe share your environment variables that you're using to setup the printer?

**Comment by DrPsychick** [comment]
Hmm, this lgtm. The `lpadmin` command should be executed and you should see with every start of the container something like this in the logs:

`... POST /admin/ HTTP/1.1" 200 185563 CUPS-Add-Modify-Printer successful-ok`

Then at least the printer should be configured in CUPS (not necessarily in Avahi yet).

From your initial post: I just double checked the permission denied message of Avahi and I was mistaken - I don't see that in my logs so maybe this is causing issues, but if so, it should only prevent the printer from appearing for AirPrint. I am running the docker container "privileged", so that might also be worth a try if that solves the issue.

As I personally don't use docker-compose, maybe you want to try if it works with pure docker. If so, then likely docker-compose does sth. differently which causes the issue.

**Comment by xavier7179** [comment]
Actually, I solved one thing and I'm still struggling with the other one. Regarding the null file, it is mandatory to add the -v option to the `lpadmin` (in the configuration) to link the printer with the `usb://<path>` path. This way, if you start the container and the printer is already on, it seems to work (I checked few times, so I hope it was not something else).

Regarding the on and off, I found this [post](https://unix.stackexchange.com/questions/216223/how-to-make-cups-show-a-usb-printer-as-disabled-when-it-is-disconnected). Unfortunately, I'm still not able to make it work because the `udev` folder is cleaned when the docker goes down...

**Comment by master-ang** [comment]
I also encountered a similar problem. Whenever I turned off the printer and turned it on again, I was prompted to Waiting for printer to become available when printing.I need to restart docker.  Is there any solution?

**Comment by xavier7179** [comment]
@master-ang did you try what I suggested before?
The solution looks fine, but it is still not the final one: after a while, without tracking the issue down, despite the USB printer correctly recognized inside the container, it stops working, and the only viable solution is to restart the container. I hope someone can jump in and suggest some adjustments.

**Comment by master-ang** [comment]
@master-ang 

/dev/bus/usb:/dev/bus/usb is working. Now I can restart the printer without restarting the container. Thank you~

**Comment by DrPsychick** [comment]
As this depends on the users setup, the only thing I did now was mentioning it in the Readme (linking to this thread). Any user can mount volumes into the existing container to make USB printers work nicely, so I don't see the need to adjust the image itself.

**Comment by master-ang** [comment]
but in QNAP ContainerStation it's not a option. I can't mount root volumes in the GUI. So, either I use the command line method, or I create a symbolic link to solve this indirectly.I hope this mount can be built into the image, so that it can be a lot more convenient.

**Comment by DrPsychick** [comment]
I understand. However, the image is a docker image. Any integration with QNAP (which I'm using myself) or other specific integrations is not part of the image and never will be.

I use my ansible role https://github.com/DrPsychick/ansible-docker to "deploy" the docker container to my QNAP. That makes it quite easy to maintain and I only use the UI rarely.

FYI: my `vars/cups.yaml` looks like this (there you could simply add your `--volume` to the create_parameters:
```yaml
containers:
  cups:
    hosts: ["neb"]
    name: "cups"
    basedir: "/share/VMs/docker"
    directory: "cups"
    owner: "admin"
    group: "administrators"
    image: "drpsychick/airprint-bridge"
    version: "latest"
    pull: yes
    create: yes
    restart: yes
    cleanup: yes
    templates:
      cupsenv: { name: "cups.env", mode: "0644" }
    # reuses network of dnsmasq-zion-neb!
    pre_command: "if [ -z \"$(docker network ls | grep qnet-static-bond0-dnsmasq)\" ]; then docker network create --driver=qnet --ipam-driver=qnet --ipam-opt=iface=bond0 --subnet 192.168.1.0/24 --gateway 192.168.1.1 qnet-static-bond0-dnsmasq; fi"
    create_parameters: "--network qnet-static-bond0-dnsmasq --ip 192.168.1.201 --dns 192.168.1.254 --hostname cups.zion --env-file cups.env --privileged --memory 200m -p 137:137/udp -p 139:139/tcp -p 445:445/tcp -p 631:631/tcp -p 5353:5353/udp"
    restart_policy: "always"
    ip: 192.168.1.201
```

**Comment by xavier7179** [comment]
> @xavier7179
> 
> /dev/bus/usb:/dev/bus/usb is working. Now I can restart the printer without restarting the container. Thank you~
> 
> I hope that @DrPsychick will improve in the next version.

Please let us know if it keeps working. As I was saying, the AirPrint part is still not stable on my side, and it does not pick the printer all the time.

**Comment by master-ang** [comment]
It keeps working ， I often turn off the printer for days, and when I turn it on again it airprints fine.

**Comment by xavier7179** [comment]
Just to check it, is it your configuration in the docker-compose like this:
```
 cups:
      container_name: cups
      image: drpsychick/airprint-bridge
      restart: unless-stopped
      hostname: cups.home
      privileged: true
      networks:
        localnet:
          ipv4_address: $CUPSSERVER_LOCALNET_IP
          #security_opt:
          #  - no-new-privileges:true
      ports:
         - "137:137/udp"
         - "139:139/tcp"
             - "445:445/tcp"
         - "631:631/tcp"
         - "5353:5353/udp"
      environment:
         TZ: $TZ
         CUPS_ADMIN_USER: $CUPS_USERNAME
         CUPS_ADMIN_PASSWORD: $CUPS_PASSWORD
         CUPS_REMOTE_ADMIN: "yes"
         CUPS_WEBINTERFACE: "yes"
         CUPS_SHARE_PRINTERS: "yes"
         CUPS_ACCESS_LOGLEVEL: "access"
         CUPS_LOGLEVEL: "debug"
         CUPS_LPADMIN_PRINTER1: "lpadmin -p <printer_model> -D '<printer_name>' -m '<printer_driver>' -v 'usb://<interface_path>'"
         CUPS_LPADMIN_PRINTER1_ENABLE: "cupsenable <printer_name>"
         CUPS_LPADMIN_PRINTER1_ACCEPT: "cupsaccept <printer_name>"
      volumes:
         - $DOCKERDIR/cups/config:/etc/cups
         - $DOCKERDIR/cups/services:/etc/avahi/services
         - /var/run/dbus:/var/run/dbus
         - /dev/bus/usb:/dev/bus/usb
         - /etc/udev:/etc/udev
```
