### ISSUE TITLE
Printers are not created on initial start/container setup, only on subsequent restarts

### ISSUE THREAD

**Issue by mundschenk-at** [DrPsychick/docker-cups-airprint#53]
I'd like to use the ENV method to create my printers. Unfortunately, the script does not seem to evaluate the ENV variables correctly on initialization of a container, but it does on subsequent restarts. I'm not sure why from reading the startup script, but there seems to be an issue with one of the `cupsctl` calls, which probably breaks the subshell.

```text
...
.--> CUPS ready
cupsctl: Unable to connect to server: Bad file descriptor
E [01/Nov/2022:05:22:08 +0000] Unable to communicate with avahi-daemon: Daemon not running
===========================================================
The dockerized CUPS instance is now ready for use! The web
interface is available here:
...
```

whereas on restart the relevant part of the log looks like this:

```text
.--> CUPS ready
localhost - - [01/Nov/2022:19:42:43 +0000] "PUT /admin/conf/cupsd.conf HTTP/1.1" 401 0 - -
localhost - root [01/Nov/2022:19:42:43 +0000] "PUT /admin/conf/cupsd.conf HTTP/1.1" 201 4614 - -
E [01/Nov/2022:19:42:43 +0000] Unable to communicate with avahi-daemon: Daemon not running
localhost - - [01/Nov/2022:19:42:43 +0000] "PUT /admin/conf/cupsd.conf HTTP/1.1" 401 0 - -
localhost - root [01/Nov/2022:19:42:43 +0000] "PUT /admin/conf/cupsd.conf HTTP/1.1" 201 4614 - -
E [01/Nov/2022:19:42:43 +0000] Unable to communicate with avahi-daemon: Daemon not running
localhost - - [01/Nov/2022:19:42:43 +0000] "PUT /admin/conf/cupsd.conf HTTP/1.1" 401 0 - -
localhost - root [01/Nov/2022:19:42:43 +0000] "PUT /admin/conf/cupsd.conf HTTP/1.1" 201 4614 - -
E [01/Nov/2022:19:42:43 +0000] Unable to communicate with avahi-daemon: Daemon not running
localhost - - [01/Nov/2022:19:42:43 +0000] "PUT /admin/conf/cupsd.conf HTTP/1.1" 401 0 - -
localhost - root [01/Nov/2022:19:42:43 +0000] "PUT /admin/conf/cupsd.conf HTTP/1.1" 201 4614 - -
E [01/Nov/2022:19:42:43 +0000] Unable to communicate with avahi-daemon: Daemon not running
localhost - - [01/Nov/2022:19:42:43 +0000] "PUT /admin/conf/cupsd.conf HTTP/1.1" 401 0 - -
localhost - root [01/Nov/2022:19:42:43 +0000] "PUT /admin/conf/cupsd.conf HTTP/1.1" 201 4640 - -
E [01/Nov/2022:19:42:43 +0000] Unable to communicate with avahi-daemon: Daemon not running
localhost - - [01/Nov/2022:19:42:43 +0000] "PUT /admin/conf/cupsd.conf HTTP/1.1" 401 0 - -
localhost - root [01/Nov/2022:19:42:43 +0000] "PUT /admin/conf/cupsd.conf HTTP/1.1" 201 4640 - -
E [01/Nov/2022:19:42:43 +0000] Unable to communicate with avahi-daemon: Daemon not running
localhost - - [01/Nov/2022:19:42:43 +0000] "PUT /admin/conf/cupsd.conf HTTP/1.1" 401 0 - -
localhost - root [01/Nov/2022:19:42:43 +0000] "PUT /admin/conf/cupsd.conf HTTP/1.1" 201 4662 - -
--> adding printers
E [01/Nov/2022:19:42:43 +0000] Unable to communicate with avahi-daemon: Daemon not running
CUPS_LPADMIN_PRINTER1 = lpadmin ...
===========================================================
The dockerized CUPS instance is now ready for use! The web
interface is available here:
```

The time difference is because the container got recreated by Portainer this morning and I did a manual restart just now.

**Comment by DrPsychick** [comment]
I have checked my installation and I cannot confirm your observation. Can you share your configuration and platform, to narrow down the potential cause?

**Comment by mundschenk-at** [comment]
Sure, I'm running this on a Synology NAS (x64) via `docker-compose`:

```yaml
version: "3"
services:
  AirPrint:
    container_name: airprint
    domainname: (...)
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - CUPS_WEBINTERFACE=yes
      - CUPS_REMOTE_ADMIN=no
      - CUPS_ENV_DEBUG=no
      - CUPS_LPADMIN_PRINTER1=lpadmin -p LaserJet (...)      
      - CUPS_LPADMIN_PRINTER1_ENABLE=cupsenable LaserJet
      - CUPS_LPADMIN_PRINTER1_ACCEPT=cupsaccept LaserJet

    hostname: airprint
    image: drpsychick/airprint-bridge:latest
    ipc: shareable
    logging:
      driver: db
      options: {}
    networks:
      - macvlan
    restart: unless-stopped
networks:
  macvlan:
      external: true
```
